---
author: iCesofT
title: "Setup de un Mac para Desarrollo"
date: 2025-12-10T10:00:00+02:00
description: "Guía para configurar un Mac para desarrollo de software"
draft: false
featured: true
toc: true
categories:
  - Desarrollo
tags:
  - Desarrollo
  - MacOS
slug: setup-mac
---

== Introducción

En este post, exploraremos los pasos esenciales para configurar un Mac para el desarrollo de software. Cubriremos desde la instalación de herramientas básicas hasta la configuración de entornos específicos para distintos lenguajes de programación.

== Herramientas Esenciales

=== Homebrew

https://brew.sh[Homebrew] es un gestor de paquetes para macOS que facilita la instalación de software. Para instalar Homebrew, abre la terminal y ejecuta el siguiente comando:

[source,bash]
----
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
----

==== Aplicaciones recomendadas

A continuación, se listan algunas aplicaciones recomendadas para instalar mediante Homebrew (para instalar, ejecutar `brew install <nombre_aplicación>`).

===== Aplicaciones de control de versiones y desarrollo

[qanda]
`brew install git-flow`::
    Extensión para Git que facilita el flujo de trabajo.
`brew install gh`::
    Herramienta de línea de comandos para interactuar con GitHub.
`brew install sourcetree`::
    https://www.sourcetreeapp.com/[Sourcetree], cliente gráfico para Git y Mercurial.

===== Aplicaciones de contenedores y virtualización

[qanda]
`brew install k9s`::
    https://k9scli.io/[k9s], interfaz de usuario para gestionar clústeres de Kubernetes.
`brew install kubernetes-cli`::
    Herramienta de línea de comandos para Kubernetes.
`brew install openlens`::
    Herramienta para trabajar con entornos de Kubernetes.

===== Aplicaciones de bases de datos

[qanda]
`brew install dbeaver-community`::
    https://dbeaver.io/[DBeaver], cliente de base de datos universal.

===== Aplicaciones de pruebas de APIs

[qanda]
`brew install bruno`::
    https://www.usebruno.com/[Bruno], herramienta para probar APIs.
`brew install postman`::
    https://www.postman.com/[Postman], herramienta para probar APIs.
`brew install soapui`::
    https://www.soapui.org/[SoapUI], herramienta para probar servicios web SOAP y REST.

===== Aplicaciones de productividad y utilidades

[qanda]
`brew install drawio`::
    https://www.drawio.com/[Draw.io], herramienta para crear diagramas y gráficos.
`brew install iterm2`::
    https://iterm2.com/[iTerm2], emulador de terminal avanzado.
`brew install keepassxc`::
    https://keepassxc.org/[KeePassXC], gestor de contraseñas seguro.
`brew install keka`::
    https://www.keka.io/es/[Keka], herramienta para comprimir y descomprimir archivos.
`brew install wget`::
    Herramienta para descargar archivos desde la web.
`brew install zettlr`::
    https://www.zettlr.com/[Zettlr], aplicación para tomar notas y gestionar referencias.
`brew install zsh-completions`::
    Complementos para Zsh que mejoran la autocompletación.

===== Aplicaciones de desarrollo

[qanda]
`brew install miniconda`::
    https://www.anaconda.com/docs/getting-started/miniconda/main[Miniconda], distribución ligera de Python con gestión de entornos.
`brew install plantuml`::
    Herramienta para crear diagramas a partir de texto.

===== Aplicaciones de nube

[qanda]
`brew install awscli`::
    https://aws.amazon.com/es/cli/[AWS CLI], herramienta de línea de comandos para gestionar servicios de AWS.
`brew install azure-cli`::
    Herramienta de línea de comandos para gestionar servicios de Azure.

===== Aplicaciones de procesamiento de datos

[qanda]
`brew install jq`::
    Herramienta para procesar JSON desde la línea de comandos.
`brew install xq`::
    Herramienta para procesar XML desde la línea de comandos.

===== Aplicaciones de IA

[qanda]
`brew install claude`::
    https://claude.ai/[Claude], herramienta de línea de comandos para interactuar con el modelo de lenguaje Claude.
`brew install lm-studio`::
    https://lmstudio.ai/[LM Studio], herramienta para gestionar modelos de lenguaje locales.
`brew install ollama`::
    https://ollama.com/[Ollama], herramienta para gestionar modelos de lenguaje locales.

=== Oh My Zsh

https://ohmyz.sh[Oh My Zsh] es un framework de código abierto para gestionar la configuración de Zsh. Proporciona una gran cantidad de plugins y temas que mejoran la experiencia en la terminal. Para instalar Oh My Zsh, abre la terminal y ejecuta el siguiente comando:

[source,bash]
----
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
----

==== Configuración de plugins

Después de instalar Oh My Zsh, puedes habilitar plugins editando el archivo `~/.zshrc`. Los plugins recomendados serían:

[source,bash]
----
plugins=(
  brew
  conda
  docker
  docker-compose
  gh
  git
  git-flow
  iterm2
  k9s
  kubectl
  macos
  mvn
  python
  sdk
  vscode
  history-substring-search
  zsh-autosuggestions
  zsh-syntax-highlighting
)

source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
----

La lista de plugins puede ajustarse según las necesidades del desarrollador. https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins[Aquí] puedes encontrar una lista completa de plugins disponibles y sus descripciones.

==== Tema recomendado: powerlevel10k

https://github.com/romkatv/powerlevel10k[Powerlevel10k] es un tema para Zsh que proporciona una apariencia visual atractiva y altamente personalizable para la terminal. Para instalar Powerlevel10k, puedes usar Homebrew:

[source,bash]
----
brew install powerlevel10k
----

A continuación, se ejecuta el asistente de configuración:

[source,bash]
----
p10k configure
----

=== SDKMAN!

https://sdkman.io[SDKMAN!] es una herramienta para gestionar múltiples versiones de SDKs para lenguajes de programación como Java, Groovy, Scala, Kotlin, entre otros. Para instalar SDKMAN!, abre la terminal y ejecuta el siguiente comando:

[source,bash]
----
curl -s "https://get.sdkman.io" | bash
----

A partir de aquí, puedes instalar y gestionar diferentes versiones de SDKs según tus necesidades. Puedes ver el listado de aplicaciones disponibles con el comando: `sdk list`.

==== Herramientas recomendadas

A continuación las herramientas recomendadas para instalar mediante SDKMAN! (para instalar, ejecutar `sdk install <nombre_herramienta> [<versión]`).

[qanda]
`sdk install java 25.0.1-librca`::
    Plataforma de desarrollo Java versión 25.
`sdk install java 21.0.9-librca`::
    Plataforma de desarrollo Java versión 21.
`sdk install java 17.0.17-librca`::
    Plataforma de desarrollo Java versión 17.
`sdk install maven`::
    Herramienta para gestionar proyectos y dependencias Maven.
`sdk install mcs`::
    Herramienta para buscar y gestionar dependencias de proyectos Maven.
